config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  get 'welcome/index'
  get 'welcome/show'
  get 'welcome/search_history'
  devise_for :users

  root 'welcome#index'

end

app/models/search_history.rb
class SearchHistory < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
require 'mylastfm'
class WelcomeController < ApplicationController

  before_action :authenticate_user!, only: :search_history
  def index
    if !params['search'].nil?
      limit=10
      @artist_hash = lastfm_connection.get_search_from_artist(params['search'],'page'=>params[:page],'limit'=>limit)
      puts @artist_hash
      @search_term= @artist_hash['results']['opensearch:Query']['searchTerms']
      @total_results=@artist_hash['results']['opensearch:totalResults']
      @no_of_pages=@total_results.to_i / limit
      @artist_list=@artist_hash['results']['artistmatches']['artist']

      if user_signed_in?
        search=SearchHistory.find_or_initialize_by(user: current_user,keyword:params['search'])
        search.update_attributes(updated_at:Time.now)
        search.save!
      end
    end
  end

  def show
    if params['name']
      @artist_info=lastfm_connection.get_getinfo_from_artist(params['name'])
      @artist_basic_info=@artist_info['artist']
      @artist_suggestions=@artist_info['artist']['similar']['artist']
      if @artist_suggestions.is_a?(Hash)
        @artist_suggestions=[@artist_suggestions]
      end
      @artist_tags=@artist_info['artist']['tags']['tag']
      if @artist_tags.is_a?(Hash)
        @artist_tags=[@artist_tags]
      end
      @artist_bio=@artist_info['artist']['bio']
      @artist_top_tracks=lastfm_connection.get_gettoptracks_from_artist(params['name'],:limit => 5)
      @artist_top_tracks_info=@artist_top_tracks['toptracks']['track']
      if @artist_top_tracks_info.is_a?(Hash)
        @artist_top_tracks_info=[@artist_top_tracks_info]
      end

    end
  end

  def search_history
    @search_history=SearchHistory.where(user: current_user).order(updated_at: :desc)
  end
  private
  def lastfm_connection
    api_key=ENV['API_KEY']
    if !api_key.nil?
      LastFM.connect(api_key)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :class => "flash_#{name}"

app/views/layouts/_navigation.html.slim
ul.nav
  li
    = link_to 'Home', root_path
  == render 'layouts/navigation_links'

= form_tag(welcome_index_path, method: :get) do
  = text_field(:search, :search, :name => 'search', :placeholder => 'search', :required => true, :value =>params['search'], :class => 'search-field')
  = hidden_field(:search, :page, :name => 'page', :value => '1')
  = submit_tag 'Search', :class => 'button'

app/views/layouts/_navigation_links.html.slim
-if user_signed_in?
  li
    = link_to 'Edit account', edit_user_registration_path
  li
    = link_to 'History', welcome_search_history_path
  li
    = link_to 'Sign out', destroy_user_session_path, :method=>'delete'
-else
  li
    = link_to 'Sign in', new_user_session_path
  li
    = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Adwyze'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Adwyze'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/welcome/index.html.slim
- if !@artist_list.nil? and @artist_list.is_a?(Array)
  table
    thead
      tr
        th Name
        th Listeners
        th Image
    tbody
      - @artist_list.each do |element|
        tr
          td
            = link_to element['name'], welcome_show_path(params.merge(name: element['name']))
          td = element['listeners']
          td
            = image_tag(element['image'][1]['#text'].blank? ? 'http://www.icon100.com/up/3969/32/145-Male-head-hair-and-beard.png' : element['image'][1]['#text'] )

  .div align='center'
    -if !@no_of_pages.nil?
      - if params[:page].to_i == 1
        = link_to 'Next',params.merge({:page => params[:page].to_i + 1})
        '
        = link_to 'Last', params.merge({:page => @no_of_pages.to_i})
      - elsif params[:page].to_i == @no_of_pages
        = link_to 'First',params.merge({:page => 1})
        '
        = link_to 'Prev', params.merge({:page => params[:page].to_i - 1})
      - else
        = link_to 'First',params.merge({:page => 1})
        '
        = link_to 'Prev',params.merge({:page => params[:page].to_i - 1})
        '
        = link_to 'Next', params.merge({:page => params[:page].to_i + 1})
        '
        = link_to 'Last', params.merge({:page => @no_of_pages.to_i})

    h4 Total Results: #{@total_results}  Number of Pages: #{@no_of_pages}
-elsif user_signed_in?
  h2 Hi #{current_user.email}

app/views/welcome/search_history.html.slim
-if @search_history.empty?
  h2 align='center'
    |You haven't started searching yet!!!
-else
  ul
    - @search_history.each do |x|
      li
        | You searched for &nbsp;
        =link_to x.keyword,welcome_index_path(search:x.keyword, page:1)
        | &nbsp; on #{x.updated_at.strftime('%c')}

app/views/welcome/show.html.slim
h2 align="center" #{@artist_basic_info['name']}

table
  tr
    td
      = image_tag(@artist_basic_info['image'][3]['#text'].blank? ? 'http://www.icon100.com/up/3969/32/145-Male-head-hair-and-beard.png' : @artist_basic_info['image'][3]['#text'] )
    td
      p #{@artist_bio['summary'].html_safe}

-if !@artist_tags.nil?
  h3 |Tracks
  table
    thead
      th
        |  Name
      th
        |  Duration
      th
        |  Playcount
      th
        |  Listeners
    tbody
      - @artist_top_tracks_info.each do |element|
        tr
          td
            | #{element['name']}
          td
            | #{element['duration'].to_i.divmod(60)[0]}:#{element['duration'].to_i.divmod(60)[1]}
          td
            | #{element['playcount']}
          td
            | #{element['listeners']}

-if !@artist_tags.nil?
  h3 |Tags
  table
    tr
      - @artist_tags.each do |element|
        td
          = link_to(element['name'],element['url'], :target => '_blank')

-if !@artist_suggestions.nil?
  h3 | Similar Artist
  /Publishing only Name and link of the similar artist and not summary and listener details as
  /it will increase the no of API calls on that page
  table
    tr
    - @artist_suggestions.each do |element|
      td
        = link_to(image_tag(element['image'][1]['#text'].blank? ? 'http://www.icon100.com/up/3969/32/145-Male-head-hair-and-beard.png' : element['image'][1]['#text']),welcome_show_url(params.merge(name: element['name'])))